### ISSUE TITLE
Line string does not produce snap effect during editing

### ISSUE THREAD

**Issue by ShareQiu1994** [mhsattarian/mapbox-gl-draw-snap-mode#1]
Hello，Line string does not produce snap effect during editing.  How can I solve it?

**Comment by ShareQiu1994** [comment]
![Uploading dev.gif…]()

**Comment by ShareQiu1994** [comment]
![dev](https://user-images.githubusercontent.com/19948086/102569410-65f13e80-4120-11eb-98af-f440063be3a5.gif)

**Comment by mhsattarian** [comment]
Hi @ShareQiu1994, you're right, snapping takes effect only when drawing, I was planning to make it work during editing as well when I had the time.
till then, I would appreciate a PR if you managed to fix this.

**Comment by AndreiBatinasVlad** [comment]
Hey guys! Any news on this? Thank you 🤗

**Comment by mhsattarian** [comment]
Hey folks, thanks to @jozefbalun, this is fixed in #7.
so I close this issue but feel free to re-open it if there is a problem.
