### ISSUE TITLE
مشکل در استفاده در پروژه React + Typesciprt

### ISSUE THREAD

**Issue by Hosseinpour6572** [mhsattarian/mapbox-gl-draw-snap-mode#6]
من تو ریکت تایپ اسکریپت نمیتونم ازش استفاده کنم لطفا راهنمایی کنید

**Comment by mhsattarian** [comment]
به چه مشکلی بر می‌خورین؟

**Comment by Hosseinpour6572** [comment]
من فرانت کار نیستم خیلی وارد نیستم  همون اول که ایمپورت میکنم با این مشکل مواجه میشم به نظرم بخاط تایپ اسکریپته
Could not find a declaration file for module 'mapbox-gl-draw-snap-mode'. 'D:/Project/xxx_panel/node_modules/mapbox-gl-draw-snap-mode/dist/mapbox-gl-draw-snap-mode.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/mapbox-gl-draw-snap-mode` if it exists or add a new declaration (.d.ts) file containing `declare module 'mapbox-gl-draw-snap-mode';`ts(7016)

**Comment by Hosseinpour6572** [comment]
و کلی از
ERROR in ./node_modules/mapbox-gl-draw-snap-mode/src/modes/snap_line.js 3:0-73
Module not found: Error: Can't resolve '@mapbox/mapbox-gl-draw/src/modes/draw_line_string' in 'D:\Project\xxx_panel\node_modules\mapbox-gl-draw-snap-mode\src\modes'    



ERROR in ./src/map/MapboxMap.tsx 18:17-27
export 'MapboxDraw' (imported as 'MapboxDraw') was not found in 'mapbox-gl-draw-snap-mode' (possible exports: SnapDirectSelect, SnapLineMode, SnapModeDrawStyles, SnapPointMode, SnapPolygonMode)

**Comment by mhsattarian** [comment]
متاسفانه هنوز type defenition نداره این پکیج. 
می‌تونین موقتا یا خودتون تایپ ماژول رو توی یک فایل `.d.ts` معرفی کنین:
```js
declare module 'mapbox-gl-draw-snap-mode';
```

یا با استفاده از کامنت‌های زیر به Typescript بگین که تایپ مربوطه رو در نظر نگیره.
```
// @ts-ignore
```

**Comment by Hosseinpour6572** [comment]
خیلی ممنون از لطف شما
🙏🙏🌺

**Comment by mhsattarian** [comment]
قربان شما. 🙏
